import { ChessColor } from './ChessBoard';
import { getRange } from './CoordinateHelper';
import { GameMode, GameOptions } from './Game';

export interface GameLevel {
  id?: number;
  name: string;
  section: string;
  color: ChessColor;
  squares: string[];
  mode: GameMode;
  pointsRequired: number;
  opts?: Partial<GameOptions>;
}

export const levels: GameLevel[] = [
  {
    name: 'Level 1',
    section: 'Humble Beginnings',
    color: 'white',
    mode: 'pick-square',
    squares: getRange('a1', 'd4'),
    pointsRequired: 0,
    id: 1,
  },
  {
    name: 'Level 2',
    section: 'Humble Beginnings',
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a1', 'd4'),
    pointsRequired: 0,
    id: 2,
  },
  {
    name: 'Level 3',
    section: 'Humble Beginnings',
    color: 'black',
    mode: 'pick-square',
    squares: getRange('a1', 'd4'),
    pointsRequired: 1,
    id: 3,
  },
  {
    name: 'Level 4',
    section: 'Humble Beginnings',
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a1', 'd4'),
    pointsRequired: 2,
    id: 4,
  },
  {
    name: 'Level 5',
    section: 'This Corner of the World',
    color: 'white',
    mode: 'pick-square',
    squares: getRange('a5', 'd8'),
    pointsRequired: 3,
    id: 5,
  },
  {
    name: 'Level 6',
    section: 'This Corner of the World',
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a5', 'd8'),
    pointsRequired: 4,
    id: 6,
  },
  {
    name: 'Level 7',
    section: 'This Corner of the World',
    color: 'black',
    mode: 'pick-square',
    squares: getRange('a5', 'd8'),
    pointsRequired: 5,
    id: 7,
  },
  {
    name: 'Level 8',
    section: 'This Corner of the World',
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a5', 'd8'),
    pointsRequired: 6,
    id: 8,
  },

  {
    name: 'Trials 1',
    section: 'Halfway House',
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a1', 'd8'),
    pointsRequired: 8,
    id: 9,
  },
  {
    name: 'Trials 2',
    section: 'Halfway House',
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a1', 'd8'),
    pointsRequired: 8,
    id: 10,
  },
  {
    name: 'Trials 3',
    section: 'Halfway House',
    color: 'white',
    mode: 'pick-square',
    squares: getRange('a1', 'd8'),
    pointsRequired: 8,
    id: 11,
  },
  {
    name: 'Trials 4',
    section: 'Halfway House',
    color: 'black',
    mode: 'pick-square',
    squares: getRange('a1', 'd8'),
    pointsRequired: 8,
    id: 12,
  },

  {
    name: 'Level 9',
    section: "It's hip to be Square",
    color: 'white',
    mode: 'pick-square',
    squares: getRange('e1', 'h4'),
    pointsRequired: 12,
    id: 13,
  },
  {
    name: 'Level 10',
    section: "It's hip to be Square",
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('e1', 'h4'),
    pointsRequired: 12,
    id: 14,
  },
  {
    name: 'Level 11',
    section: "It's hip to be Square",
    color: 'black',
    mode: 'pick-square',
    squares: getRange('e1', 'h4'),
    pointsRequired: 13,
    id: 15,
  },
  {
    name: 'Level 12',
    section: "It's hip to be Square",
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('e1', 'h4'),
    pointsRequired: 14,
    id: 16,
  },
  {
    name: 'Level 13',
    section: 'The Last Dance',
    color: 'white',
    mode: 'pick-square',
    squares: getRange('e5', 'h8'),
    pointsRequired: 15,
    id: 17,
  },
  {
    name: 'Level 14',
    section: 'The Last Dance',
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('e5', 'h8'),
    pointsRequired: 16,
    id: 18,
  },
  {
    name: 'Level 15',
    section: 'The Last Dance',
    color: 'black',
    mode: 'pick-square',
    squares: getRange('e5', 'h8'),
    pointsRequired: 17,
    id: 19,
  },
  {
    name: 'Level 16',
    section: 'The Last Dance',
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('e5', 'h8'),
    pointsRequired: 18,
    id: 20,
  },

  {
    name: 'Trials 5',
    section: 'Show Me Your Might',
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('e1', 'h8'),
    pointsRequired: 20,
    id: 21,
  },
  {
    name: 'Trials 6',
    section: 'Show Me Your Might',
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('e1', 'h8'),
    pointsRequired: 20,
    id: 22,
  },
  {
    name: 'Trials 7',
    section: 'Show Me Your Might',
    color: 'white',
    mode: 'pick-square',
    squares: getRange('e1', 'h8'),
    pointsRequired: 20,
    id: 23,
  },
  {
    name: 'Trials 8',
    section: 'Show Me Your Might',
    color: 'black',
    mode: 'pick-square',
    squares: getRange('e1', 'h8'),
    pointsRequired: 20,
    id: 24,
  },

  {
    name: 'Exam 1',
    section: 'Bring It Home',
    color: 'white',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a1', 'h8'),
    pointsRequired: 24,
    id: 25,
  },
  {
    name: 'Exam 2',
    section: 'Bring It Home',
    color: 'black',
    mode: 'pick-coords',
    opts: { target: 15 },
    squares: getRange('a1', 'h8'),
    pointsRequired: 24,
    id: 26,
  },
  {
    name: 'Exam 3',
    section: 'Bring It Home',
    color: 'white',
    mode: 'pick-square',
    squares: getRange('a1', 'h8'),
    pointsRequired: 24,
    id: 27,
  },
  {
    name: 'Exam 4',
    section: 'Bring It Home',
    color: 'black',
    mode: 'pick-square',
    squares: getRange('a1', 'h8'),
    pointsRequired: 24,
    id: 28,
  },
];
